version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: sitthichai
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: rct_account
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres-data: